# Generated by Django 4.2.2 on 2023-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='subtitle',
        ),
    ]
